### ISSUE TITLE
Node createtables.js is not found

### ISSUE THREAD

**Issue by jaurelius** [asterisk/node-voicemail-admin#3]
When running node-voicemail-admin for the first time you are directed to "Exit now and run ‘node createtables.js’ if the database has not been initialized.

When attempting to run 'node createtables.js' the system reports that it can not find module node-voicemail-admin/createtables.js

How should a sqlite database be created?

**Comment by jrrose** [comment]
You know, I thought this script was in there, but apparently it's been lost somewhere. My apologies, I'll be adding this some time soon.

In the meantime, All I can offer you is a table dump from my postgresql database.

http://pastebin.com/2pcw4cp1

**Comment by jaurelius** [comment]
Thank you, I will work with this table dump and watch for the script to be
posted.

**Comment by jrrose** [comment]
Hey, posted this patch. If you are still wanting to play with this, feel free to give it a shot!
